name: Atualizar Licitações

# Define quando o workflow deve rodar
on:
  schedule:
    - cron: '0 16 * * 4' # Toda quinta-feira às 16:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      # Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Run the Python script
      - name: Run update script
        run: python Dados/coleta_api.py

      # Check for changes and commit if there are any
      - name: Check for changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if git diff --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi

      - name: Commit and push changes
        if: success()
        run: |
          git add Dados/contratos_OFICIAL.json
          git commit -m "Atualização automática: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
