name: Atualizar CNPJs

on:
  workflow_run:
    workflows: ["Atualizar Licitações"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-cnpjs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run CNPJ script
        run: python Dados/coleta_cnpjs.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply.github.com'
          git pull origin main
          git add Dados/infos_cnpj_OFICIAL.json
          git commit -m "Atualização automática: $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nada para commitar"
          git push
