name: Atualizar CNPJs

on:
  push:
    branches:
      - main
    paths:
      - 'Dados/contratos_OFICIAL.json'
      - 'Dados/**'

jobs:
  update-cnpjs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run CNPJ script
        run: python Dados/coleta_cnpjs.py

      - name: Check for changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply.github.com'
          if git diff --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi

      - name: Commit and push changes
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin main
          git add Dados/infos_cnpj_OFICIAL.json
          git commit -m "Atualização automática: $(date +'%Y-%m-%d %H:%M:%S')"
          git push